name: Build-Docs

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]

    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: cd docs && npm install
      - name: Build
        run: cd docs && npm run-script build
