name: Alpha-Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]

    steps:
      - uses: actions/checkout@v2
      - name: Install Misk-Web
        run: sudo npm install -g @misk/cli
      - name: Misk-Web Prebuild
        run: miskweb prebuild -e
      - name: Configure git user
        run: |
          git config user.name Misk-Web Alpha Release Bot
          git config user.email misk-web+robots@squareup.com
      - name: Rush bump version
        run: node common/scripts/install-run-rush.js version --bump
      - name: Rush publish
        run: node common/scripts/install-run-rush.js publish --include-all -a -p -n ${NPM_PUBLISH_TOKEN}
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: Install strip-json-comments-cli && jq
        run: npm install --global strip-json-comments-cli && sudo apt-get install jq
      - name: Commit version changes
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: "[ALPHA-RELEASE $(cat common/config/rush/version-policies.json | strip-json-comments | jq '.version')]"
